name: Build and Deploy Docker image

on:
  push:
    branches:
      - master  # o el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliza un runner en Ubuntu
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # Obtiene el código fuente del repositorio

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Configura Docker Buildx para construir la imagen

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}  # Usuario de DockerHub
        password: ${{ secrets.DOCKERHUB_PASSWORD }}  # Contraseña de DockerHub
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/react-games:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to digitalocean
      uses: appleboy/ssh-action@master
      with:
        username: ${{ vars.HOSTING_USERNAME }}
        host: ${{ vars.HOSTING_PC }}
        key: ${{ secrets.HOSTING_KEY }}
        script: |
            docker stop react-games ; 
            docker rm react-games -f ; 
            docker rmi ${{ vars.DOCKERHUB_USERNAME }}/react-games -f ; 
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/react-games
            docker run --name react-games -d -p 3096:80 ${{ vars.DOCKERHUB_USERNAME }}/react-games 